/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author fabri
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonGenciamentoAmb = new javax.swing.JButton();
        jButtonGerenciamentoDipos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Fundo2 = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuUsuario = new javax.swing.JMenu();
        jMenuItemUsuario = new javax.swing.JMenuItem();
        jMenuItemCadastroAmbientes = new javax.swing.JMenuItem();
        jMenuItemCadastroDipositivos = new javax.swing.JMenuItem();
        jMenuItemComandoVoz = new javax.swing.JMenuItem();
        jMenuGerenciamento = new javax.swing.JMenu();
        jMenuItemDipositivos = new javax.swing.JMenuItem();
        jMenuItemAmbientes = new javax.swing.JMenuItem();
        jMenuManutencao = new javax.swing.JMenu();
        jMenuItemPermissoes = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");
        setResizable(false);
        getContentPane().setLayout(null);

        jButtonGenciamentoAmb.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonGenciamentoAmb.setText("Ambientes");
        jButtonGenciamentoAmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenciamentoAmbActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGenciamentoAmb);
        jButtonGenciamentoAmb.setBounds(30, 180, 150, 40);

        jButtonGerenciamentoDipos.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonGerenciamentoDipos.setText(" Dispositivos");
        jButtonGerenciamentoDipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerenciamentoDiposActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGerenciamentoDipos);
        jButtonGerenciamentoDipos.setBounds(30, 120, 150, 40);

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Benvindo A Tela Principal");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 0, 400, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gerenciamento");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 70, 200, 20);

        Fundo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Casa2.png"))); // NOI18N
        Fundo2.setText("jLabel2");
        getContentPane().add(Fundo2);
        Fundo2.setBounds(-140, 0, 1000, 600);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EUiYD-lWoAAF9mO.jpg"))); // NOI18N
        getContentPane().add(Fundo);
        Fundo.setBounds(0, -10, 730, 470);

        jMenuUsuario.setText("Cadastros");

        jMenuItemUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemUsuario.setText("Usuário");
        jMenuItemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuarioActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuItemUsuario);

        jMenuItemCadastroAmbientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCadastroAmbientes.setText("Ambientes");
        jMenuItemCadastroAmbientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroAmbientesActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuItemCadastroAmbientes);

        jMenuItemCadastroDipositivos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCadastroDipositivos.setText("Dipositivos");
        jMenuItemCadastroDipositivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroDipositivosActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuItemCadastroDipositivos);

        jMenuItemComandoVoz.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemComandoVoz.setText("Comando De Voz");
        jMenuItemComandoVoz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemComandoVozActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuItemComandoVoz);

        jMenuBar1.add(jMenuUsuario);

        jMenuGerenciamento.setText("Gerenciamento");

        jMenuItemDipositivos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemDipositivos.setText("Dispositivos");
        jMenuItemDipositivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDipositivosActionPerformed(evt);
            }
        });
        jMenuGerenciamento.add(jMenuItemDipositivos);

        jMenuItemAmbientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAmbientes.setText("Ambientes");
        jMenuItemAmbientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAmbientesActionPerformed(evt);
            }
        });
        jMenuGerenciamento.add(jMenuItemAmbientes);

        jMenuBar1.add(jMenuGerenciamento);

        jMenuManutencao.setText("Manutenção");

        jMenuItemPermissoes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_7, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemPermissoes.setText("Permissões");
        jMenuItemPermissoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPermissoesActionPerformed(evt);
            }
        });
        jMenuManutencao.add(jMenuItemPermissoes);

        jMenuBar1.add(jMenuManutencao);

        jMenuSair.setText("Sair");

        jMenuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_QUOTE, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(718, 447));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGenciamentoAmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenciamentoAmbActionPerformed
                    GerenciamentoAmbientes gerenciamento = new GerenciamentoAmbientes();
                                      gerenciamento.setVisible(true);
                        dispose();
    }//GEN-LAST:event_jButtonGenciamentoAmbActionPerformed

    private void jButtonGerenciamentoDiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerenciamentoDiposActionPerformed
                    //GerenciamentoDispositivos Gerenciamentod = new GerenciamentoDispositivos();
                                    //Gerenciamentod.setVisible(true);
                    new GerenciamentoDispositivos().show();   
                    dispose();                
    }//GEN-LAST:event_jButtonGerenciamentoDiposActionPerformed

    private void jMenuItemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioActionPerformed
                    CadastroDeUsuário cadastrou = new CadastroDeUsuário();
                                      cadastrou.setVisible(true);
                        dispose();
    }//GEN-LAST:event_jMenuItemUsuarioActionPerformed

    private void jMenuItemComandoVozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemComandoVozActionPerformed
                     CadastroComandoVoz cadastrocv = new CadastroComandoVoz();
                                     cadastrocv.setVisible(true);
                                      dispose();
    }//GEN-LAST:event_jMenuItemComandoVozActionPerformed

    private void jMenuItemCadastroAmbientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroAmbientesActionPerformed
                        CadastroAmbientes cadastroa = new CadastroAmbientes();
        cadastroa.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemCadastroAmbientesActionPerformed

    private void jMenuItemCadastroDipositivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroDipositivosActionPerformed
        // TODO add your handling code here:
                    new CadastroDispositivos().show();   
                    dispose(); 
    }//GEN-LAST:event_jMenuItemCadastroDipositivosActionPerformed

    private void jMenuItemPermissoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPermissoesActionPerformed
                     new Permissoes().show();   
                    dispose();    
    }//GEN-LAST:event_jMenuItemPermissoesActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
                     new TelaLogin().show();   
                    dispose();
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemAmbientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAmbientesActionPerformed
        // TODO add your handling code here:
            new GerenciamentoAmbientes().show();   
                    dispose(); 
    }//GEN-LAST:event_jMenuItemAmbientesActionPerformed

    private void jMenuItemDipositivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDipositivosActionPerformed
        // TODO add your handling code here:
        new GerenciamentoDispositivos().show();   
                    dispose(); 
        
    }//GEN-LAST:event_jMenuItemDipositivosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel Fundo2;
    private javax.swing.JButton jButtonGenciamentoAmb;
    private javax.swing.JButton jButtonGerenciamentoDipos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuGerenciamento;
    private javax.swing.JMenuItem jMenuItemAmbientes;
    private javax.swing.JMenuItem jMenuItemCadastroAmbientes;
    private javax.swing.JMenuItem jMenuItemCadastroDipositivos;
    private javax.swing.JMenuItem jMenuItemComandoVoz;
    private javax.swing.JMenuItem jMenuItemDipositivos;
    private javax.swing.JMenuItem jMenuItemPermissoes;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemUsuario;
    private javax.swing.JMenu jMenuManutencao;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu jMenuUsuario;
    // End of variables declaration//GEN-END:variables
}
